package:
  name: scipy
  version: 0.17.0

source:
  url: https://pypi.python.org/packages/source/s/scipy/scipy-0.17.0.tar.gz
  fn: scipy-0.17.0.tar.gz

requirements:
  build:
    - python
    - cython
    - nomkl
    - openblas
    - numpy

  run:
    - libgcc
    - python
    - openblas
    - numpy

build:
  number: 102

  features:
    - nomkl
    - openblas

about:
  home: https://www.scipy.org
  license: PSF
