package:
  name: numpy
  version: 1.10.2

source:
  url: https://github.com/numpy/numpy/archive/v1.10.2.tar.gz
  fn: numpy-1.10.2.tar.gz

requirements:
  build:
    - python
    - openblas 

  run:
    - python
    - openblas

build:
  number: 102

  features:
    - openblas

about:
  home: https://www.numpy.org
  license: PSF
